### ISSUE TITLE
VKD3D Update to fix NVIDIA GPUs Freezing Computers

### ISSUE THREAD

**Issue by Arcitec** [bottlesdevs/components#231]
Hi @mirkobrombin !

I've got some very important news about VKD3D. :)

There are two NVIDIA driver bugs that freeze/crash the entire computer when playing DX12 games.

NVIDIA are aware of it. And VKD3D added workarounds for both bugs two days ago:

https://github.com/HansKristian-Work/vkd3d-proton/issues/1389#issuecomment-1483937991

It's therefore important to update VKD3D to latest Git, since right now, Bottles can't play DX12 games on NVIDIA GPUs.

**Comment by Bananaman** [comment]
Extra info: Newest build cannot be done in Wine 8.4 due to bugs in that version of Wine. Use 8.0 or similar "older" version of Wine to do the build.

https://github.com/HansKristian-Work/vkd3d-proton/issues/1487

**Comment by koplo199** [comment]
vkd3d-proton will be updated automatically on March 28, but as recent builds including the fix fails on the official repository (from which the [build artifacts](https://github.com/HansKristian-Work/vkd3d-proton/actions/workflows/artifacts.yml?query=branch%3Amaster) are pulled), that update will likely also not include the fix unless there is a successful run before the fatidic date.

A successful build on the official repository is what is needed, as an update could be manually triggered after that, but looking at the vkd3d-proton workflow file it probably won't happen until wine 8.5 is available on the arch repository.

**Comment by Bananaman** [comment]
@koplo199 Ahh so the updates are automated here based on the vkd3d-proton repo?

Hopefully wine 8.5 will be out soon since they seem to do 2-3 week intervals between updates right now:

https://www.winehq.org/news/

And thank you for the research and pull request regarding d3d12core.dll! :)

In the meantime, people who are affected by the VKD3D crashes can go into Bottles, "manage environment variables" and set the following variable:

- `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_id,VK_KHR_present_wait`

It will take care of the same issue. Just remember to remove it later when VKD3D updates to the latest version, which handles this automatically (until the day NVIDIA has fixed the bug; they're aware of it).

**Comment by koplo199** [comment]
> Ahh so the updates are automated here based on the vkd3d-proton repo?

Yes, [most components are](https://github.com/bottlesdevs/components/actions). Updates are pulled every morning and are applied immediately for official/stable releases, or every 2 weeks for unstable/experimental builds.

**Comment by koplo199** [comment]
I believe this issue could be closed as the vkd3d-proton component has been updated with the fix since the issue was created
