### ISSUE TITLE
Vaniglia updates?

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/components#264]
I mentioned this in another issue but it got no answers, so I'm posting it here instead.

In Bottles Preferences->Runners, the latest "Vaniglia" version offered is 7.18, but in https://github.com/bottlesdevs/wine/releases there's several newer versions available. Why aren't these offered through Bottles?

That releases page is also a bit confusing. The releases are not in release date order. E.g. `Soda 7.0-9`, released in Feb 5, 2023, is listed after `Vaniglia 7.18`, released in Sep 27, 2022.

***

Side question: Have I understood correctly that at the moment, if the user wants to use the latest Wine runners, the only option is the kron4ek runners? It seems to update pretty fast to new Wine versions. Is there a point to release Vaniglia runner?

**Comment by koplo199** [comment]
> In Bottles Preferences->Runners, the latest "Vaniglia" version offered is 7.18, but in https://github.com/bottlesdevs/wine/releases there's several newer versions available. Why aren't these offered through Bottles?

The reason is that `Vaniglia` builds aren't automatically updated CI, and that nobody did a PR to include them manually.

I'll try to integrate them to the CI in a later revision, if those builds are still relevant at that point, which as we'll see later isn't certain.

> That releases page is also a bit confusing. The releases are not in release date order. E.g. Soda 7.0-9, released in Feb 5, 2023, is listed after Vaniglia 7.18, released in Sep 27, 2022.

Yes, I agree this is confusing.

The reason is that GitHub does not order releases by release date, but instead by the date of the most recent commit of the main branch at release time. Soda and Caffe are built in their own branch, thus the commit on the main branch does not change between versions, and it messes with the ordering of releases. This phenomenon is visible in this page: https://github.com/bottlesdevs/wine/tags

> Side question: Have I understood correctly that at the moment, if the user wants to use the latest Wine runners, the only option is the kron4ek runners? It seems to update pretty fast to new Wine versions. Is there a point to release Vaniglia runner?

The most frequently updated runners currently are `Wine-GE` and `Kron4ek` builds.

Lately, I investigated and it seems `Vaniglia` builds are fundamentally very similar to Kron4ek wine-staging builds.

Additionnaly, it seems `Vaniglia` currently have its fair share of issues:

https://github.com/bottlesdevs/wine/issues/54
https://github.com/bottlesdevs/wine/issues/51
https://github.com/bottlesdevs/wine/issues/50

So I don't know what are the plans for `Vaniglia` for the future, but at the moment it's pretty much a dead end.
